///try-catch.

// try{

    //normal code

// }catch(err){ //err is error object.

    //handling error

// }

let a=100;
let b=500;

console.log("a=",a);
console.log("b=",b);
console.log("a+b=",a+b);
console.log("a-b=",a-b);
try{
console.log("a+c=",a+c);
}
catch(err)//err is error object.
{ 
    console.log(err)
}
console.log("a*b=",a*b);
console.log("a/b=",a/b);
console.log("a%b=",a%b);
